{% set name = "tantivy" %}
{% set version = "0.22.2" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.org/packages/source/{{ name[0] }}/{{ name }}/tantivy-{{ version }}.tar.gz
  sha256: b3d0f19271365ccf6e69f0318ea0c3c3438515fee453618977787d6b41da833a

build:
  script: {{ PYTHON }} -m pip install . -vv --no-deps --no-build-isolation
  number: 0

requirements:
  build:
    - {{ compiler("c") }}
    - {{ stdlib("c") }}
    - {{ compiler("rust") }}
    - cargo-bundle-licenses
    - pkg-config
  host:
    - python
    - maturin <=1.3.2
    - pip
  run:
    - python

test:
  imports:
    - tantivy
  commands:
    - pip check
  requires:
    - pip

about:
  summary: Python bindings for Tantivy
  home: https://github.com/quickwit-oss/tantivy-py
  license: MIT
  license_file: LICENSE

extra:
  recipe-maintainers:
    - jan-janssen
