{% set name = "tantivy" %}
{% set version = "0.25.0" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.org/packages/source/{{ name[0] }}/{{ name }}/tantivy-{{ version }}.tar.gz
  sha256: 587acbaa08a6287eaa7591c21bc5af5a577c8a3c347b1121032241a5912f17b6

build:
  script: {{ PYTHON }} -m pip install . -vv --no-deps --no-build-isolation
  number: 0
  skip: true  # [py>=313]

requirements:
  build:
    - {{ compiler("c") }}
    - {{ stdlib("c") }}
    - {{ compiler("rust") }}
    - cargo-bundle-licenses
    - pkg-config
  host:
    - python
    - maturin <=1.3.2
    - pip
  run:
    - python

test:
  imports:
    - tantivy
  commands:
    - pip check
  requires:
    - pip

about:
  summary: Python bindings for Tantivy
  home: https://github.com/quickwit-oss/tantivy-py
  license: MIT
  license_file: LICENSE

extra:
  recipe-maintainers:
    - jan-janssen
