{% set name = "tantivy" %}
{% set version = "0.22.0" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.org/packages/source/{{ name[0] }}/{{ name }}/tantivy-{{ version }}.tar.gz
  sha256: dce07fa2910c94934aa3d96c91087936c24e4a5802d839625d67edc6d1c95e5c

build:
  script: {{ PYTHON }} -m pip install . -vv --no-deps --no-build-isolation
  number: 1

requirements:
  build:
    - {{ compiler("c") }}
    - {{ stdlib("c") }}
    - {{ compiler("rust") }}
    - cargo-bundle-licenses
    - pkg-config
  host:
    - python
    - maturin <=1.3.2
    - pip
  run:
    - python

test:
  imports:
    - tantivy
  commands:
    - pip check
  requires:
    - pip

about:
  summary: Python bindings for Tantivy
  home: https://github.com/quickwit-oss/tantivy-py
  license: MIT
  license_file: LICENSE

extra:
  recipe-maintainers:
    - jan-janssen
